### PR TITLE
chore: release aws-jupyter-proxy 0.3.2

### PR DESCRIPTION
**Pull request by danpilgrim-aws**
Releases aws-jupyter-proxy 0.3.2

*Description of changes:*
Changes version number in setup file, uses github workflows release process.

Releases the following commits:
- https://github.com/aws/aws-jupyter-proxy/commit/4dbfdfd8ba32c3127ad076c6e9757b628a33b070
- https://github.com/aws/aws-jupyter-proxy/commit/65fe5ca6d97b53999fa6fa6e8289745a434d1539
- https://github.com/aws/aws-jupyter-proxy/pull/20
- 
- https://jira.hil.aws.dev/browse/AXIS-1472

### CODE REVIEW

**Review by aakashmandavilli — APPROVED** [review]
Version bump changes from 0.3.1 to 0.3.2

**Comment by declanvk** [comment]
Hey @danpilgrim-aws , looking at the previous commits to bump the version I think they have a version tag applied, of the form `v<version-number>`, like `v0.3.1`. See https://github.com/aws/aws-jupyter-proxy/commit/7a5b73b4714a552903ce16afdacc6abe60824df4 . Since tags are not applied on a PR, I think we need to locally create this commit + tag and push to `master` directly.

I think the workflows need the tag attached to the commit or else they will not run the publish steps, see https://github.com/aws/aws-jupyter-proxy/blob/7f1918b5cc0524d15fa213eddc95f998ff540282/.github/workflows/test-and-publish.yml#L42-L54

cc @aakashmandavilli

**Comment by declanvk** [comment]
Alright, I've pushed a version of this commit with a tag attached to `master`, need to wait and see if it releases correctly

**Comment by declanvk** [comment]
The change has been released, see:
 - https://pypi.org/project/aws-jupyter-proxy/0.3.2/
 - https://github.com/aws/aws-jupyter-proxy/actions/runs/2863681534

I now realize I could have merged and then push a tag, but this also did the trick. The release has been made

**Pull request closed without merging**
